version: '3.8'

services:
  dbpostgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: clientes_db
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

volumes:
  dbpostgres_data:
